# Spring framework configuration
spring:
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: order-service
                fallbackuri: forward:/failed/order-service/redirect
        - id: pizza-service
          uri: lb://pizza-service
          predicates:
            - Path=/pizza/**
          filters:
            - name: CircuitBreaker
              args:
                name: pizza-service
                fallbackuri: forward:/failed/pizza-service/redirect
        - id: security-jwt-service
          uri: lb://security-jwt-service
          predicates:
            - Path=/security/jwt/**
          filters:
            - name: CircuitBreaker
              args:
                name: security-jwt-service
                fallbackuri: forward:/failed/security-jwt-service/redirect
        - id: security-oauth-service
          uri: lb://security-oauth-service
          predicates:
            - Path=/security/oauth/**
          filters:
            - name: CircuitBreaker
              args:
                name: security-oauth-service
                fallbackuri: forward:/failed/security-oauth-service/redirect

# Swagger integration library used to centralize the documentation to every microservice
# For dev profile, the required url to access it is:
#   http://localhost:5555/swagger-ui/
springfox:
  documentation:
    swagger:
      # Custom property to include the path of documented microservices using Swagger v3
      v3:
        # Api docs path properties
        path: /v3/api-docs
      # Custom property to include the documented microservices using Swagger
      documentedServices: security-jwt-service,pizza-service,order-service
      # Custom property to include the documented API version
      apiVersion: 1.0
